# Generated by Django 5.0.2 on 2024-03-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='treated',
            field=models.BooleanField(default=False),
        ),
    ]
